### PR TITLE
Use DocStringExtensions template

### PR DESCRIPTION
**Pull request by daniel-thom**

### CODE REVIEW

**Comment by kdheepak** [comment]
Is there a preview of the documentation generated from the PR?

**Comment by daniel-thom** [comment]
I don't think so.  Here's a screenshot.

image

**Comment by kdheepak** [comment]
Docs are failing to be pushed.

https://github.com/NREL-SIIP/InfrastructureSystems.jl/runs/823650150#step:5:89

**Comment by kdheepak** [comment]
Docs seem to be deploying fine on master, so I'm rerunning these jobs.

**Pull request merged**
